site_name: Notes
site_url: http://docs.romanempire.dev/
site_author: Roman Podkovyrin
site_description: >-
  Documentation in Markdown of my notes

repo_url: https://github.com/RomanPodkovyrin/Notes
repo_name: Notes


copyright: Copyright &copy; Roman Podkovyrin
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RomanPodkovyrin
  # alternate:
  #   - name: English
  #     link: / #/en/ 
  #     lang: en
  #   - name: Russian
  #     link: /ru/
  #     lang: ru
      
theme:
  features:
    - search.suggest
    # No page reload breaks latex formatting 
    #- navigation.instant
    #- navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.footer
    # - toc.integrate
    - navigation.top
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    # - navigation.indexes
    # - navigation.tabs.sticky
    # - navigation.sections
  logo: assets/duck-logo-noboarders.png
  favicon: assets/duck-logo-noboarders.png
  language: en
  name: material #mkdocs #readthedocs
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    #      # Palette toggle for light mode
    # - scheme: default
    #   primary: white
    #   accent: indigo
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/weather-night
    #     name: Switch to light mode
  # color_mode: dark
  
plugins:
  - search

markdown_extensions:
  - tables
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      # title: On this page
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
        alternate_style: true
        slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Languages:
    - languages/index.md
    - Go: languages/go/go.md
    - Java: 
      - Java: languages/java/java.md
      - Java 8 (LTS): languages/java/java8.md
      - Java 9: languages/java/java9.md
      - Java 10: languages/java/java10.md
      - Java 11 (LTS): languages/java/java11.md
      - Java 12: languages/java/java12.md
      - Java 13: languages/java/java13.md
      - Java 14: languages/java/java14.md
      - Java 15: languages/java/java15.md
      - Java 16: languages/java/java16.md
      - Java 17 (LTS): languages/java/java17.md
      - Java 18: languages/java/java18.md
      - Java 19: languages/java/java19.md
      - Java 20: languages/java/java20.md
      - Java 21 (LTS): languages/java/java21.md
      
    - Javascript: 
      - Vanila JS: languages/js/js.md
      - TypeScript: languages/typescript/typescript.md
    - Kotlin: languages/kotlin/kotlin.md
    - Python: languages/python/python.md
    - Leetcode:
      - Blind 75:
          - Array:
              - Two Sum: languages/leetcode/blind75/array/two-sum.md
              - Best Time to Buy and Sell Stock: languages/leetcode/blind75/array/best-time-buy-sell-stock.md
              - Contains Duplicate: languages/leetcode/blind75/array/contains-duplicate.md
              - Product of Array Except Self: languages/leetcode/blind75/array/product-array-except-self.md
              - Maximum Subarray: languages/leetcode/blind75/array/maximum-subarray.md
              - Maximum Product Subarray: languages/leetcode/blind75/array/maximum-product-subarray.md
              - Find Minimum in Rotated Sorted Array: languages/leetcode/blind75/array/find-min-rotated-sorted-array.md
              - Search in Rotated Sorted Array: languages/leetcode/blind75/array/search-rotated-sorted-/languages/leetcode/blind75/array.md
              - 3 Sum: array/3-sum.md
              - Container With Most Water: languages/leetcode/blind75/array/container-most-water.md
          - Binary:
              - Sum of Two Integers: languages/leetcode/blind75/binary/sum-two-integers.md
              - Number of 1 Bits: languages/leetcode/blind75/binary/number-1-bits.md
              - Counting Bits: languages/leetcode/blind75/binary/counting-bits.md
              - Missing Number: languages/leetcode/blind75/binary/missing-number.md
              - Reverse Bits: languages/leetcode/blind75/binary/reverse-bits.md
          - Dynamic Programming:
              - Climbing Stairs: languages/leetcode/blind75/dp/climbing-stairs.md
              - Coin Change: languages/leetcode/blind75/dp/coin-change.md
              - Longest Increasing Subsequence: languages/leetcode/blind75/dp/longest-increasing-subsequence.md
              - Longest Common Subsequence: languages/leetcode/blind75/dp/longest-common-subsequence.md
              - Word Break Problem: languages/leetcode/blind75/dp/word-break-problem.md
              - Combination Sum: languages/leetcode/blind75/dp/combination-sum.md
              - House Robber: languages/leetcode/blind75/dp/house-robber.md
              - House Robber II: languages/leetcode/blind75/dp/house-robber-ii.md
              - Decode Ways: languages/leetcode/blind75/dp/decode-ways.md
              - Unique Paths: languages/leetcode/blind75/dp/unique-paths.md
              - Jump Game: languages/leetcode/blind75/dp/jump-game.md
          - Graph:
              - Clone Graph: languages/leetcode/blind75/graph/clone-graph.md
              - Course Schedule: languages/leetcode/blind75/graph/course-schedule.md
              - Pacific Atlantic Water Flow: languages/leetcode/blind75/graph/pacific-atlantic-water-flow.md
              - Number of Islands: languages/leetcode/blind75/graph/number-of-islands.md
              - Longest Consecutive Sequence: languages/leetcode/blind75/graph/longest-consecutive-sequence.md
              - Alien Dictionary: languages/leetcode/blind75/graph/alien-dictionary.md
              - Graph Valid Tree: languages/leetcode/blind75/graph/graph-valid-tree.md
              - Number of Connected Components in an Undirected Graph: languages/leetcode/blind75/graph/number-connected-components.md
          - Interval:
              - Insert Interval: languages/leetcode/blind75/interval/insert-interval.md
              - Merge Intervals: languages/leetcode/blind75/interval/merge-intervals.md
              - Non-overlapping Intervals: languages/leetcode/blind75/interval/non-overlapping-intervals.md
              - Meeting Rooms: languages/leetcode/blind75/interval/meeting-rooms.md
              - Meeting Rooms II: languages/leetcode/blind75/interval/meeting-rooms-ii.md
          - Linked List:
              - Reverse a Linked List: languages/leetcode/blind75/linked-list/reverse-linked-list.md
              - Detect Cycle in a Linked List: languages/leetcode/blind75/linked-list/detect-cycle.md
              - Merge Two Sorted Lists: languages/leetcode/blind75/linked-list/merge-two-sorted-lists.md
              - Merge K Sorted Lists: languages/leetcode/blind75/linked-list/merge-k-sorted-lists.md
              - Remove Nth Node From End Of List: languages/leetcode/blind75/linked-list/remove-nth-node.md
              - Reorder List: languages/leetcode/blind75/linked-list/reorder-list.md
          - Matrix:
              - Set Matrix Zeroes: languages/leetcode/blind75/matrix/set-matrix-zeroes.md
              - Spiral Matrix: languages/leetcode/blind75/matrix/spiral-matrix.md
              - Rotate Image: languages/leetcode/blind75/matrix/rotate-image.md
              - Word Search: languages/leetcode/blind75/matrix/word-search.md
          - String:
              - Longest Substring Without Repeating Characters: languages/leetcode/blind75/string/longest-substring.md
              - Longest Repeating Character Replacement: languages/leetcode/blind75/string/longest-repeating-character-replacement.md
              - Minimum Window Substring: languages/leetcode/blind75/string/minimum-window-substring.md
              - Valid Anagram: languages/leetcode/blind75/string/valid-anagram.md
              - Group Anagrams: languages/leetcode/blind75/string/group-anagrams.md
              - Valid Parentheses: languages/leetcode/blind75/string/valid-parentheses.md
              - Valid Palindrome: languages/leetcode/blind75/string/valid-palindrome.md
              - Longest Palindromic Substring: languages/leetcode/blind75/string/longest-palindromic-substring.md
              - Palindromic Substrings: languages/leetcode/blind75/string/palindromic-substrings.md
              - Encode and Decode Strings: languages/leetcode/blind75/string/encode-decode-strings.md
          - Tree:
              - Maximum Depth of Binary Tree: languages/leetcode/blind75/tree/maximum-depth.md
              - Same Tree: languages/leetcode/blind75/tree/same-tree.md
              - Invert/Flip Binary Tree: languages/leetcode/blind75/tree/invert-binary-tree.md
              - Binary Tree Maximum Path Sum: languages/leetcode/blind75/tree/binary-tree-maximum-path-sum.md
              - Binary Tree Level Order Traversal: languages/leetcode/blind75/tree/binary-tree-level-order-traversal.md
              - Serialize and Deserialize Binary Tree: languages/leetcode/blind75/tree/serialize-deserialize-binary-tree.md
              - Subtree of Another Tree: languages/leetcode/blind75/tree/subtree-another-tree.md
              - Construct Binary Tree from Preorder and Inorder Traversal: languages/leetcode/blind75/tree/construct-binary-preorder-inorder.md
              - Validate Binary Search Tree: languages/leetcode/blind75/tree/validate-bst.md
              - Kth Smallest Element in a BST: languages/leetcode/blind75/tree/kth-smallest-bst.md
              - Lowest Common Ancestor of BST: languages/leetcode/blind75/tree/lowest-common-ancestor-bst.md
              - Implement Trie (Prefix Tree): languages/leetcode/blind75/tree/implement-trie.md
              - Add and Search Word: languages/leetcode/blind75/tree/add-search-word.md
              - Word Search II: languages/leetcode/blind75/tree/word-search-ii.md
          - Heap:
              - Merge K Sorted Lists: languages/leetcode/blind75/heap/merge-k-sorted-lists.md
              - Top K Frequent Elements: languages/leetcode/blind75/heap/top-k-frequent-elements.md
              - Find Median from Data Stream: languages/leetcode/blind75/heap/find-median-data-stream.md
        
  - DevOps: 
    - devops/index.md
    - Cloud: 
      - Azure: 
        - AZ-900: devops/cloud/azure/az-900/az-900.md
    - Containerisation: 
      - Docker Compose: devops/containerisation/docker-compose.md
  - Security: 
    - security/index.md
    - Authentication: security/authentication/authentication.md
    - Threat Modelling: security/threat-modelling/threat-modelling.md
  - Software Engineering: 
    - architecture/index.md
    - Version Control System (VCS): 
      - GIT: architecture/vcs/git/git.md
    - Data Structures & Algorithms:
      - architecture/data-structures-and-algorithms/index.md
      - Complexity: architecture/data-structures-and-algorithms/complexity/complexity.md
      - Algorithms: architecture/data-structures-and-algorithms/algorithms/algorithms.md
      - Structures: architecture/data-structures-and-algorithms/structures/structures.md
    - Software Development Patterns: 
      - 12 Factor Apps: architecture/patterns/12-factor-app/12-factor-app.md
      - Test Driven Development: architecture/patterns/tdd/tdd.md
    - Testing: architecture/testing/testing.md
    - System Design:
      - architecture/system-design/index.md
      - Computer Architecture: architecture/system-design/computer-architecture.md
      - High-level Architecture: architecture/system-design/architecture.md
      - Design: architecture/system-design/design.md
      - Networking: architecture/system-design/networking.md
      - API: architecture/system-design/api.md
      - Caching and CDN: architecture/system-design/caching-cdn.md
      - Proxy: architecture/system-design/proxy.md
      - Databases:  architecture/system-design/databases.md
      - OOP: architecture/system-design/oop.md
  - Web Development and Backend:
    - web-dev-and-backend/index.md
    - API Architecture: 
      - REST: web-dev-and-backend/api/rest/rest.md
      - GraphQL: web-dev-and-backend/api/graphql/graphql.md
    - Backend: 
      - Databases: web-dev-and-backend/backend/databases/db.md
      # - Frameworks: 
      #   - Springboot: 
    - Web Development:
      - web-dev-and-backend/web/web.md
  # - About: about.md
  
    
    