site_name: Notes
site_url: http://docs.romanempire.dev/
site_author: Roman Podkovyrin
site_description: >-
  Documentation in Markdown of my notes

repo_url: https://github.com/RomanPodkovyrin/Notes
repo_name: Notes


copyright: Copyright &copy; Roman Podkovyrin
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RomanPodkovyrin
  # alternate:
  #   - name: English
  #     link: / #/en/ 
  #     lang: en
  #   - name: Russian
  #     link: /ru/
  #     lang: ru
      
theme:
  features:
    - search.suggest
    # No page reload breaks latex formatting 
    #- navigation.instant
    #- navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.footer
    # - toc.integrate
    - navigation.top
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    # - navigation.indexes
    # - navigation.tabs.sticky
    # - navigation.sections
  logo: assets/duck-logo-noboarders.png
  favicon: assets/duck-logo-noboarders.png
  language: en
  name: material #mkdocs #readthedocs
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    #      # Palette toggle for light mode
    # - scheme: default
    #   primary: white
    #   accent: indigo
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/weather-night
    #     name: Switch to light mode
  # color_mode: dark
  
plugins:
  - search

markdown_extensions:
  - tables
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      # title: On this page
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
        alternate_style: true
        slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Languages:
    - languages/index.md
    - Go: languages/go/go.md
    - Java: 
      - Java: languages/java/java.md
      - Java 8: languages/java/java8.md
    - Javascript: 
      - Vanila JS: languages/js/js.md
      - TypeScript: languages/typescript/typescript.md
    - Kotlin: languages/kotlin/kotlin.md
    - Python: languages/python/python.md
  - DevOps: 
    - devops/index.md
    - Cloud: 
      - Azure: 
        - AZ-900: devops/cloud/azure/az-900/az-900.md
    - Containerisation: 
      - Docker Compose: devops/containerisation/docker-compose.md
  - Security: 
    - security/index.md
    - Authentication: security/authentication/authentication.md
  - Software Engineering: 
    - architecture/index.md
    - Version Control System (VCS): 
      - GIT: architecture/vcs/git/git.md
    - Data Structures & Algorithms: 
      - Complexity: architecture/data-structures-and-algorithms/complexity/complexity.md
      - Algorithms: architecture/data-structures-and-algorithms/algorithms/algorithms.md
      - Structures: architecture/data-structures-and-algorithms/structures/structures.md
    - Software Development Patterns: 
      - 12 Factor Apps: architecture/patterns/12-factor-app/12-factor-app.md
      - Test Driven Development: architecture/patterns/tdd/tdd.md
    - Testing: architecture/testing/testing.md
    - System Design: architecture/system-design/system-design.md
  - Web Development and Backend:
    - web-dev-and-backend/index.md
    - API Architecture: 
      - REST: web-dev-and-backend/api/rest/rest.md
      - GraphQL: web-dev-and-backend/api/graphql/graphql.md
    - Backend: 
      - Databases: web-dev-and-backend/backend/databases/db.md
      # - Frameworks: 
      #   - Springboot: 
    - Web Development:
      - web-dev-and-backend/web/web.md
  # - About: about.md
  
    
    